### ISSUE TITLE
Incorrect Get Repo link

### ISSUE THREAD

**Issue by lemacomb** [IBM/Portfolio-Optimize#13]
Step one of this starter kit has the wrong link for getting the repo.  The current (incorrect) link is: https://github.ibm.com/arf/starter-finance-portfolio-optimize#1-clone-the-repo

not sure if this is the correct link to the repository ... https://github.com/IBM/Portfolio-Optimize

**Comment by raheelzubairy** [comment]
Have made the correction.  Thanks
